export const destinationModel = () => ({
  req_group_name: "",
  req_book_name: "",
  req_book_email: "",
  req_book_phone: "",
  req_book_pass: "",
  req_book_pass_confirm: "",
  req_bid: 0,
  req_bid_end: 0,
  req_hotel: 0,
  req_depart: "",
  req_arr: "",
  req_main_group: 0,
  req_adults: 0,
  req_kids: 0,
  req_infant: 0,
  req_opt: "",
  is_read: 0,
  created_at: new Date(), // Initializes to the current date
  updated_at: new Date(), // Initializes to the current date
  qu_sta: 0,
  req_depart_period: 0,
  req_arr_period: 0,
  req_inc_food: 0,
  req_vehicle: 0,
  req_mode: 0,
  goal_selected: "",
  theme_selected: [],
  trip_req: [],
  room_selected: [],
  favor_food: [],
  strict_list: [],
  addition_list: [],
});
